services:
  - type: web
    name: rtfbot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: WEBHOOK_URL
        sync: false
